using ClosedXML.Excel;
using EMS.Application.Abstractions;
using EMS.Application.Reporting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace EMS.Web.Controllers;

/// <summary>Section 14 (UI) / 13.7-13.9 (spec) - reports landing page, parameter panel, grid and export.</summary>
[Authorize]
public class ReportsController : Controller
{
    private readonly IReportService _reportService;
    private readonly IPermissionService _permissions;

    public ReportsController(IReportService reportService, IPermissionService permissions)
    {
        _reportService = reportService;
        _permissions = permissions;
    }

    public async Task<IActionResult> Index(CancellationToken ct)
    {
        ViewData["Title"] = "Reports";
        ViewData["Breadcrumb"] = new List<(string, string?)> { ("Dashboard", "/"), ("Reports", null) };

        var catalogue = await _reportService.GetCatalogueAsync(ct);
        return View(catalogue.GroupBy(c => c.Category).ToList());
    }

    public async Task<IActionResult> Run(string code, DateOnly? asOf, string? financialYear, long? shareholderId, CancellationToken ct)
    {
        // 13.9.5 - report access requires an explicit permission.
        if (!await _permissions.CurrentUserHasPermissionAsync(Permissions.ReportsView, ct))
            return Forbid();

        ViewData["Title"] = code;
        ViewData["Breadcrumb"] = new List<(string, string?)> { ("Dashboard", "/"), ("Reports", Url.Action("Index")), (code, null) };

        var parameters = new ReportParameters(asOf, financialYear, null, shareholderId, null);
        var result = await _reportService.RunAsync(code, parameters, ct);
        return View(result);
    }

    public async Task<IActionResult> ExportExcel(string code, DateOnly? asOf, string? financialYear, long? shareholderId, CancellationToken ct)
    {
        // 13.9.5 - export is a separate permission from view.
        if (!await _permissions.CurrentUserHasPermissionAsync(Permissions.ReportsExport, ct))
            return Forbid();

        var result = await _reportService.RunAsync(code, new ReportParameters(asOf, financialYear, null, shareholderId, null), ct);

        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add(result.Title.Length > 31 ? result.Title[..31] : result.Title);

        for (var i = 0; i < result.Columns.Count; i++)
            sheet.Cell(1, i + 1).Value = result.Columns[i].Header;
        sheet.Row(1).Style.Font.Bold = true;

        var r = 2;
        foreach (var row in result.Rows)
        {
            for (var i = 0; i < result.Columns.Count; i++)
            {
                var value = row.GetValueOrDefault(result.Columns[i].Key);
                if (value is decimal or int) sheet.Cell(r, i + 1).Value = Convert.ToDouble(value);
                else sheet.Cell(r, i + 1).Value = value?.ToString() ?? "";
            }
            r++;
        }
        sheet.Columns().AdjustToContents();

        var meta = workbook.Worksheets.Add("Metadata");
        meta.Cell(1, 1).Value = "Report"; meta.Cell(1, 2).Value = result.Title;
        meta.Cell(2, 1).Value = "Generated"; meta.Cell(2, 2).Value = result.GeneratedAtUtc.ToString("u");
        meta.Cell(3, 1).Value = "Generated by"; meta.Cell(3, 2).Value = result.GeneratedByUserId;
        meta.Cell(4, 1).Value = "Filters"; meta.Cell(4, 2).Value = result.FilterSummary;
        meta.Cell(5, 1).Value = "Confidentiality"; meta.Cell(5, 2).Value = "Confidential - CB Bank Internal Use";
        meta.Cell(6, 1).Value = "Developed by"; meta.Cell(6, 2).Value = "Sunfix";

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);

        var fileName = $"EMS_{code}_{DateTime.UtcNow:yyyyMMdd-HHmmss}.xlsx";
        return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
    }

    public async Task<IActionResult> ExportPdf(string code, DateOnly? asOf, string? financialYear, long? shareholderId, CancellationToken ct)
    {
        if (!await _permissions.CurrentUserHasPermissionAsync(Permissions.ReportsExport, ct))
            return Forbid();

        var result = await _reportService.RunAsync(code, new ReportParameters(asOf, financialYear, null, shareholderId, null), ct);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Landscape());
                page.Margin(24);
                page.DefaultTextStyle(x => x.FontSize(9));

                page.Header().Column(col =>
                {
                    col.Item().Text("EQUITY MANAGEMENT SYSTEM").Bold().FontSize(14).FontColor(Colors.Blue.Darken3);
                    col.Item().Text(result.Title).FontSize(12);
                    col.Item().Text($"Generated: {result.GeneratedAtUtc:dd MMM yyyy HH:mm} UTC | By: {result.GeneratedByUserId} | Filters: {result.FilterSummary}").FontSize(8);
                });

                page.Content().PaddingVertical(10).Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        foreach (var _ in result.Columns) columns.RelativeColumn();
                    });

                    table.Header(header =>
                    {
                        foreach (var col in result.Columns)
                            header.Cell().Background(Colors.Blue.Lighten4).Padding(4).Text(col.Header).Bold();
                    });

                    foreach (var row in result.Rows)
                    {
                        foreach (var col in result.Columns)
                        {
                            var value = row.GetValueOrDefault(col.Key);
                            var cellText = table.Cell().BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(4)
                                .Text(FormatValue(value));
                            if (col.Numeric) cellText.AlignRight();
                        }
                    }
                });

                page.Footer().Row(row =>
                {
                    row.RelativeItem().Text("Confidential - CB Bank Internal Use. Developed by Sunfix.").FontSize(7);
                    row.RelativeItem().AlignRight().Text(x =>
                    {
                        x.CurrentPageNumber();
                        x.Span(" / ");
                        x.TotalPages();
                    });
                });
            });
        });

        var bytes = document.GeneratePdf();
        var fileName = $"EMS_{code}_{DateTime.UtcNow:yyyyMMdd-HHmmss}.pdf";
        return File(bytes, "application/pdf", fileName);
    }

    private static string FormatValue(object? value) => value switch
    {
        decimal d => d.ToString("N2"),
        null => "",
        _ => value.ToString() ?? ""
    };
}
